name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      with:
        major_pattern: "/major(\\(.+\\))?:/"
        minor_pattern: "/feat(\\(.+\\))?:/"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"
        bump_each_commit: true
      id: version

    - name: Docker login
      uses: docker/login-action@v4
      with: 
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build the Docker image
      run: |
        docker build -t meridaerick/graphql:0.0.1 .

    - name: Push the Docker image
      run: |
        docker push meridaerick/graphql:0.0.1
